### PR TITLE
HBIOS: Added support for sound drivers

### PR DESCRIPTION
**Pull request by vipoo**
New sound driver support with initial support for the SN76489 chip

New build configuration entry:
* SN76489ENABLE

Ports are currently locked in with:
* SN76489_PORT_LEFT       .EQU    $FC     ; PORTS FOR ACCESSING THE SN76489 CHIP (LEFT)
* SN76489_PORT_RIGHT      .EQU    $F8     ; PORTS FOR ACCESSING THE SN76489 CHIP (LEFT)

### CODE REVIEW

**Comment by wwarthen** [comment]
Thanks Dean.  Will take a little time to review first.

-Wayne

**Comment by wwarthen** [comment]
OK, everything looked good, so I have completed the merge.

I do see a few minor types.  If you could hold off on any more checkins for now, I am going to do a quick pass at that stuff.

Thanks,

Wayne

**Comment by wwarthen** [comment]
OK, I am done with my cleanup stuff.  OK for checkins again.

-Wayne

**Comment by vipoo** [comment]
Cool - i had a bit of a challenge getting the merge sorted.

I will progress slowly and cut further commits over the next few days ..

**Comment by wrljet** [comment]
When I was in college, a long time ago, my roommate got a summer intern job
at Texas Instruments, in Texas.  Where they were developing that 76489 sound chip.

He came back with a bunch of the chips, all pre-release rejects.
They worked but the attenuator was not monotonically increasing,
if that's the right term, with the powers of 2.

We wired one up to an 8080A we had built, and managed to
get the pin numbering backwards (top to bottom) when wire wrapping the socket.  Wound up bending all the pins backwards so they pointed up toward the top of the chip.

Bill

**Comment by wwarthen** [comment]
Sounds good Dean.

**Comment by vipoo** [comment]
<!--
/* Font Definitions */
@font-face
	{font-family:"Cordia New";
	panose-1:2 11 3 4 2 2 2 2 2 4;}
@font-face
	{font-family:"Cambria Math";
	panose-1:2 4 5 3 5 4 6 3 2 4;}
@font-face
	{font-family:Calibri;
	panose-1:2 15 5 2 2 2 4 3 2 4;}
/* Style Definitions */
p.MsoNormal, li.MsoNormal, div.MsoNormal
	{margin:0cm;
	margin-bottom:.0001pt;
	font-size:11.0pt;
	font-family:"Calibri",sans-serif;}
a:link, span.MsoHyperlink
	{mso-style-priority:99;
	color:blue;
	text-decoration:underline;}
.MsoChpDefault
	{mso-style-type:export-only;
	font-family:"Calibri",sans-serif;}
@page WordSection1
	{size:612.0pt 792.0pt;
	margin:72.0pt 72.0pt 72.0pt 72.0pt;}
div.WordSection1
	{page:WordSection1;}

**Pull request merged**
