### PR TITLE
bin2asm for fonts for building under linux.

### PR DESCRIPTION
**Pull request by b1ackmai1er**
Hi this adds bin2asm for building the font asm files for other platforms that use them. Hope this is all ok, I have not used linux in decades.

### CODE REVIEW

**Comment by b1ackmai1er** [comment]
Also note that I am using git on the linux box for the first time. Hope I don't screw up the repo !!!!

**Comment by wwarthen** [comment]
@cm68, would you mind reviewing this since you are doing the Linux stuff?

Thanks,

Wayne

**Comment by wwarthen** [comment]
@b1ackmai1er, it sounds like Curt has a handle on the font files and it is already a work in progress.  Would you mind if I just let @cm68 handle this for now?  Since the whole Linux/Mac makefile stuff is still so new, I would like to let him get it stable first.

OK if I pass on this specific pull request in favor of Curt's pending pull request?

Thanks,

Wayne

**Comment by b1ackmai1er** [comment]
No problem at all. Thanks Curt. It's good to have a linux box again.

**Comment by b1ackmai1er** [comment]
Curt to continue development. Let me know if you need any testing.

**Comment by wwarthen** [comment]
Thanks Phil!

**Pull request closed without merging**
