### PR TITLE
ay-3-8910 sound driver initial release

### PR DESCRIPTION
**Pull request by b1ackmai1er**

### CODE REVIEW

**Comment by wwarthen** [comment]
Hi Phil,

I don't have time to test, but  these changes look generally isolated to the AY sound driver, so I am going to merge them and make sure I see no build errors.

@dnetherton, I will assume you are following all this as well.

Thanks,

Wayne

**Comment by wwarthen** [comment]
Can ay.asm and ay38910.asm be merged?

**Comment by wwarthen** [comment]
Windows and Linux build look OK.  Further testing is up to you!  :-)

**Comment by b1ackmai1er** [comment]
hi wayne. yes will work towards that. timeout fixes to xm are a huge
improvement.

Regatds Phil

**Comment by wwarthen** [comment]
> timeout fixes to xm are a huge improvement.

Yeah, I have been much happier with XM with the timeout changes.  Wish I had done that a long time ago.

**Pull request merged**
