### PR TITLE
Sound drivers

### PR DESCRIPTION
**Pull request by vipoo**
Fixes to enable building of both the SN76489 and AY38910 drivers into 1 image - there were label conflicts.

Cleaned up the debug tracing statements that both drivers us.  Again some label conflicts - and made a little more consistent.

Not sure why yet - had not investigated, so it could be something i have done wrong - but the AY driver does not work on my RC2014 kit -- it just locks up during the init stage.  

I am not sure how to communicate with @b1ackmai1er ... i guess he has his account faily private - wise move!

Cheers
Dean

### CODE REVIEW

**Comment by wwarthen** [comment]
Looks good to me.  Same deal, I will merge and confirm all the standard builds are OK.  No time for testing right now.

Thanks,  Wayne

**Comment by wwarthen** [comment]
Standard build looks fine.  Thanks.

**Comment by b1ackmai1er** [comment]
@vipoo 

Hi Dean, Feel free to gmail me at difficultylevelhigh

I am not that familiar with github collaboration facilities so if there  is anything I need to change on my account settings please let me know.

With regard to sound driver architecture development, I think SNDNOT function should have standardized values so that regardless of which platform/sound chip is used a calling program always know how to play middle-C for example. One way would be to use the MIDI standard note. Or a query function could return note specific information like lower and upper range, middle-C and note stepping.  Let me know your thoughts on this or if I have missed something. Regards Phil

**Comment by b1ackmai1er** [comment]
@vipoo 

Hi Dean, What is your hardware/configuration/clock speed?

**Comment by vipoo** [comment]
Hi mate,

With regards to github - i dont know much myslef- i think most people put
an email address in the profile - but i can understand why most choose not
to do that.  i tried looking to raise an issue or send private message to
you - but saw no links - it might just be me.

The point you mentioned for SNDNOT is kind of how I imagined it would
work.  And i thought it be best to get as much of the calculation within
the assembler as possible - (though i learnt the assembler's preprocessor
does not do floating point numbers -- gee i am learning a lot of old
stuff!) - I wanted it to be as correct as possible, in terms of mapping to
the correct notes.

If I recall correctly, i needed 8 bits to get the range for the SN76489 - I
imagine for the AY chip - it has a larger range - so will need more?

I used my phone , with a frequency analyser - just to double check my
modelling/calculations were correct.

My hardware is a RC2014 kit -
The RC2014 kit (Spencer's Ownens kits)
* the dual clock module (7.3728) - (
https://www.tindie.com/products/Semachthemonkey/rc2014-dual-clock-module/)
the AY-3-8910 - (based on this one: (
https://www.tindie.com/products/semachthemonkey/ym2149-sound-card-for-rc2014-retro-computer/
)
and the SN76489 (based on https://github.com/jblang/SN76489)

Cheers
Dean

**Comment by b1ackmai1er** [comment]
Hi Dean, have you had sound out of your ym2149 board before. Did the original ay.asm driver work/beep when configured for rc2014? on initial release i had left sbcv2004 speed switch config in. maybe that was a problem.  What clk speed is the ym2149 being fed? are you using the internal ym2149 divider & jumper?

**Comment by vipoo** [comment]
Hi, Yep – I have had sound out of the AY board just fine.  The TUNE.COM app drives it just fine. But I do need to confirm the beep via HBIOS. I followed the default jumper settings – JP5 – set to 2/3 – divide clock by 4 I have not had time to investigate myself – let me see if I can further diagnose where it locks up – and get back to ya. Dean  Sent from Mail for Windows 10 From: b1ackmai1erSent: Tuesday, 5 May 2020 1:23 AMTo: wwarthen/RomWBWCc: Dean Netherton; MentionSubject: Re: [wwarthen/RomWBW] Sound drivers (#119) Hi Dean, have you had sound out of your ym2149 board before. Did the original ay.asm driver work/beep when configured for rc2014? on initial release i had left sbcv2004 speed switch config in. maybe that was a problem. What clk speed is the ym2149 being fed? are you using the internal ym2149 divider & jumper?  —You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by b1ackmai1er** [comment]
Hi Dean, I've submitted some updates. Can your please test on your AN76489 system. Can you also try the AY build as well. AYSND will have to be set to suit your sound module. Tune in normal mode should tell you which one. Cheers  Phil

**Comment by vipoo** [comment]
Good news - i got a note!

Great stuff.

I issued the hbios command to play using period - and got a note!

Need to have a closer look, as time permits.

I ran the automated tests, so your your code change to SN driver seems to
work just fine.

I notice, that there maybe a difference in the implementation for the NOTE
function.  The SN driver scale is quarter semi tones - I was following
something similar to the mapping the bbcbasic sound statement used - and it
seem to fit nicely in an 8bit range.

Maybe i misunderstand, but the SY driver looks to only mapping at
semitones?

(Dean listen to yourself - quarter tones, semitones --- as if you have any
idea what you are talking about)

I also wonder, if its posible to keep some of the calculation until
assembly time - to help maintain accurate notes, even if the underlying
clock is different?  If this is something you are working towards - just
tell me to wait!

I had issues trying to achieve that, as the assembler's integer only
expression are rather limiting to do the correct calculations -- but it
does work - at least for the 10bit period of the SN chip.  Not sure if the
accuracy loss will be an issue for the AY chip.

I had another look at my spreadsheet i used to model up the maths - i
really cant remember how i did it!

I will do some more testing and get back to you as soon as i can

Cheers
Dean

**Comment by b1ackmai1er** [comment]
HI Dean,

That is good to hear. I will implement the quarter tone notes and have a
look at the assembly time calculation.

Can you please confirm the device detection is working?

Regards Phil.

**Comment by vipoo** [comment]
Board detection work.

I tested with and without - and the driver only activated when installed.
When card was not inserted - got the NOT PRESENT statement for it.

Nice one.

Cheers
Dean

**Comment by b1ackmai1er** [comment]
Thanks. Just working on --hbios validation as well. Fail with error rather
than PANIC if no sound drivers found.

**Comment by b1ackmai1er** [comment]
Hi Dean, Quarter tone table implemented for BBC micro and converted to calculation. Can you please test. Thanks.

**Comment by vipoo** [comment]
Hi ya, My observations: The notes were initially not correct – as my card is clocked by 4 from CPU – once I adjusted this – things started coming out with the correct frequency (Using android app : Pitched Tuner to validate) Now it be nice to figure out how to arrange the frequency maps – so that the 2 drivers are delivering consistent octaves, as well as maximising the chips range. It doesn’t have to start at 0 – we could use the range of the AY chip – and just clip the numbers for the SN chip. Eg: NOTE 0 => maps to frequency 2914, A0# - this is basically the lowest frequency the chip can produce for my clock config: (7372800/4).  If the clock is higher, eg divider of 2, then the lowest notes are an octave higher  – and super high notes can be achieved (probably impractically high). If you like, I can have a go at getting the maps to work across the board. CheersDean Sent from Mail for Windows 10 From: b1ackmai1erSent: Saturday, 9 May 2020 11:24 AMTo: wwarthen/RomWBWCc: Dean Netherton; MentionSubject: Re: [wwarthen/RomWBW] Sound drivers (#119) Hi Dean, Quarter tone table implemented for BBC micro and converted to calculation. Can you please test. Thanks.—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by b1ackmai1er** [comment]
Hi Dean, With identical note tables both cards should produce the same tone when correct clk and divider are selected. As you were implementing compatibility with BBC micro/basic the AY38910 driver version (should) faithfully implements the BBC basic tone table i.e. 256 notes, 3 quarter notes skipped between A#1 & B1 and middle C is note 53. Or at least that was my aim, lol. Does the clock divider need more smart logic to identify system and set both accordingly.
Suggest you sync your SN76489 table with the AY38910 version as a starting point (or visa versa if you feel that is more appropriate). Beyond that, I think it would be better to implement the TUNE function as more system independent is as you suggest A0#=29.14 or use HL = H= Octave, L = Quarter / Semi tone etc and then applications such as BBC BASIC can map accordingly.  Size of tone table may be a consideration. Lemme know what you think. Since we are in Dev mode we can try different ideas. Working on converting bit banged spk driver over from nascom.asm :)

**Comment by vipoo** [comment]
I have progressed this challenge a bit – been doing some maths. I have removed the need for a full mapping table for every note – we just need a single octave mapped out. Using that, I can calculate at runtime the period for any note required.  Adjusting the scale appropriately. https://github.com/vipoo/RomWBW/commit/f24da58d850d580fb9f26ccb1871b60b9e25ead4 I have only verified with automatic tests – need to double check for real – to confirm notes are correct And then apply the same logic to the AY driver. Heres a readonly link to the spreadsheet I used to crunch the numbers: https://docs.google.com/spreadsheets/d/1KCIcESZrFp7boRRcMX7n7oCD6M0NJmq0krABSG8jsLk/edit?usp=sharing  The code note ready for a PR yet – I think I can finish this tomorrow. CheersDean  Sent from Mail for Windows 10 From: b1ackmai1erSent: Saturday, 9 May 2020 4:31 PMTo: wwarthen/RomWBWCc: Dean Netherton; MentionSubject: Re: [wwarthen/RomWBW] Sound drivers (#119) Hi Dean, With identical note tables both cards should produce the same tone when correct clk and divider are selected. As you were implementing compatibility with BBC micro/basic the AY38910 driver version (should) faithfully implements the BBC basic tone table i.e. 256 notes, 3 quarter notes skipped between A#1 & B1 and middle C is note 53. Or at least that was my aim, lol. Does the clock divider need more smart logic to identify system and set both accordingly.Suggest you sync your SN76489 table with the AY38910 version as a starting point (or visa versa if you feel that is more appropriate). Beyond that, I think it would be better to implement the TUNE function as more system independent is as you suggest A0#=29.14 or use HL = H= Octave, L = Quarter / Semi tone etc and then applications such as BBC BASIC can map accordingly. Size of tone table may be a consideration. Lemme know what you think. Since we are in Dev mode we can try different ideas. Working on converting bit banged spk driver over from nascom.asm :)—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by wwarthen** [comment]
Just wanted to say that I am very impressed with the work you both are doing on this.  This will be a major improvement in RomWBW with the next formal release.

Thanks!

Wayne

**Comment by b1ackmai1er** [comment]
Happy to have something to contribute.

Thanks to Dean for committing the API.  Would never have believed it
possible to play PT3s through a HBIOS interface :)

Regards Phil.

**Pull request merged**
