### PR TITLE
Dean/dev 6

### PR DESCRIPTION
**Pull request by vipoo**
Hi Wayne,

Some more sound driver updates:

1. Added a query function to retrieve the physical hardware ports used.
2. handle when the period is too high for the sn76489 chip - returing error and not playing anything - this seem to make the tune.com apps sound a little more correct - it simply does not play some of the lower notes, that this chip can not handle - (its no boombox!)
3.  renamed the field pitch to the correct name of period.

Cheers
Dean

### CODE REVIEW

**Comment by wwarthen** [comment]
Looks good to me Dean.

Thanks!

**Comment by b1ackmai1er** [comment]
I''m happy to work on an ay-3-8910 driver if nobody else has started it. Please let me know.

**Comment by vipoo** [comment]
Hi,

Thats cool - i had thought i might start sketching it out this weekend -
but if you are ready - please i dont want to stop anyone.

My thinking is perhaps to do the following, (just my initial thoughts ....)

1. Add new driver for the AY chip - providing support for Vol, Period and
port retrieval - as per the implementation for SN76489 chip.
2. Move and use the tune.com code as a guide for hardware detection, port
mapping for all platforms - etc.  (i am assuming no licence issues?)
3. Update tune.com to use the hardware detection and port mapping as
returned by the new driver for when running with the AY-3-8910 chip (it
would not use the driver functions for Vol, Period, Play, as those function
are only a subset of the chip)
4. Tune.com continues to use the drivers' Vol, Period and Play function for
the SN76489 chip.
5. I would like to keep the automated tests i wrote for the sound driver
working and compliant - i am happy to keep track of that as changes are
submitted.


I have been playing with the BBCBasic fork, (this is what triggered me to
add the sound support in hbios - i wanted the bbcbasic code to be able to
use the sound drivers).  So i could resume work on that, and see if i can
progress the sound support in bbcbasic.

Cheers
Dean

**Comment by b1ackmai1er** [comment]
Terrific, I will work on it over the weekend and assuming I make
substantial progress will submit to dev branch for your review,
enhancement, collaboration etc.

Regards Phil.

**Comment by wwarthen** [comment]
Really pleased to see this kind of collaboration!

Thanks,

Wayne

**Pull request merged**
