### PR TITLE
audio update

### PR DESCRIPTION
**Pull request by b1ackmai1er**
sound added to device summary
improvements to spk driver
groundwork for play duration in hbios api
audio driver initialization sequenced by capability

### CODE REVIEW

**Comment by wwarthen** [comment]
Thanks for this Phil.  Sorry for the slow response, I am in the middle of some other stuff that I will share soon.  I am looking at the changes now.

-Wayne

**Comment by wwarthen** [comment]
Quick review looks good.  Thanks Phil!

**Comment by wwarthen** [comment]
Just FYI, I updated the formatting of the Note/Octave table in the Architecture document.  Sadly, markdown does not support column spans.

**Comment by b1ackmai1er** [comment]
ta. is there an easy way to review changes before submitting?

**Comment by wwarthen** [comment]
Well, it is simple in the sense that it is just two commands.

```
pp Architecture1.md >Architecture_pp.md
pandoc Architecture_pp.md -s -o Architecture1.pdf --default-image-extension=pdf
```

The hard part is simply the installation of the required tools, which are:

- [Pandoc Preprocesor](https://github.com/CDSoft/pp)
- [Pandoc](https://pandoc.org/)
- [MiKTeX](https://miktex.org/)

The reason I do not include the documentation build process in the RomWBW distribution is that these tools consume over 1GB of disk space.  Sigh.  So, I run the document generation pipeline "out of band".

There are a bunch of markdown viewers out there.  However, they struggle with the header stuff at the top of my .md source files.  That header stuff is for Pandoc Preprocessor and Pandoc and they don't understand it because it is not markdown per se.

-Wayne

**Pull request merged**
