### PR TITLE
Some extra build config options

### PR DESCRIPTION
**Pull request by vipoo**
Hi Wayne,

Not sure if these changes are something you are interested in merging.

These are some tweaks to the build config that I have used for my custom builds and also my test builds  - to make testing just that little bit quicker.

* `BOOT_DEFAULT_FORCE`
When this is defined, and used in conjuction with `BOOT_DEFAULT`, causes the boot loader to not wait - just go for the desired bootup.
I am not 100% sure this is fully compatible with all the startup options.

* `MDRAMDISABLE`
When defined, causes the md.asm to skip the ram disk driver - ROM drive becomes A:
Had to update CBIOS to detect this - to ensure the default drive is mapped right - again - not 100% certain this is all correct - my local testing seem to indicate all is good.

* `FD_DEVCNT_OVRD`
This option can be used to cause the fd.asm to only configure 1 floppy - I only have 1 floppy on my kit - and that extra item just bugged me.

I understand and appreciate, if you dont want to merge these commits - but its here if you wish to incorporate em.

Its also possible i have misunderstood stuff - and I am not sure if there are alternatives to what i have done.

Cheers
Dean

### CODE REVIEW

**Comment by wwarthen** [comment]
Hi Dean,

This is all valid stuff, thanks.  I am going to want to carefully review all of these though.  In some cases, I may want to make minor changes for consistency with other areas of the code.  I also want to carefully assess some of these changes relative to some complex usage scenarios that may not be obvious (I have tripped myself up repeatedly).

I am probably going to merge changes by hand possibly making some minor adjustments as I go.  I will keep you posted.  Horribly overloaded right now.

Thanks,

Wayne

**Comment by wwarthen** [comment]
Hi Dean,

I have hand-merged 2 of your 3 enhancements.  One will need to wait a bit because of me.  See below.

Thanks,

Wayne

> * `BOOT_DEFAULT_FORCE`
>   When this is defined, and used in conjuction with `BOOT_DEFAULT`, causes the boot loader to not wait - just go for the desired bootup.
>   I am not 100% sure this is fully compatible with all the startup options.

I have implemented this, but used some alternative code that was already dormant in romldr.asm from a rewrite I did a couple weeks ago.  Instead of a new config variable, BOOT_TIMEOUT is used for everything.  0=Auto boot immediately, -1=Wait forever, >0=Wait N seconds, then auto boot.

Let me know if this suits your needs.

> * `MDRAMDISABLE`
>   When defined, causes the md.asm to skip the ram disk driver - ROM drive becomes A:
>   Had to update CBIOS to detect this - to ensure the default drive is mapped right - again - not 100% certain this is all correct - my local testing seem to indicate all is good.

I do want to implement this, but got too tangled up in a batch of changes I am working on offline.  I am working on support for keeping slices inside partition tables.  The changes are pervasive and I am avoiding some areas that conflict.  Can we come back to this one as soon as I get this partition table stuff published?

> * `FD_DEVCNT_OVRD`
>   This option can be used to cause the fd.asm to only configure 1 floppy - I only have 1 floppy on my kit - and that extra item just bugged me.

A long overdue change that I always intended to make.  Merged your changes directly, but used a variable called FDCNT which is more consistent with similar variables in other drivers.

> I understand and appreciate, if you don't want to merge these commits - but its here if you wish to incorporate em.

I always appreciate contributions as long as you don't mind my curation of them.  :-)  I have credited you in the changelog and the GitHub checkin.  I hope you are OK with that.

Thanks!

Wayne

**Comment by vipoo** [comment]
Hi Wayne

This is all sounds great - i kind of suspected your would have some
specific changes you would want to apply - not to mention other
priorities in the code.  Just hope i am helping and not loading you up with
lower priority changes.

Cheers
Dean

**Comment by vipoo** [comment]
Given you have manually merged - and need to defer one item - i am happy to close this PR - and raise any new changes in seperate pr - when u ready.

**Comment by wwarthen** [comment]
Sounds like a plan.  Thanks Dean.

**Pull request closed without merging**
