### PR TITLE
Alternate debug standardization method

### PR DESCRIPTION
**Pull request by b1ackmai1er**
Hi Wayne, This is an alternate approach. 
Debugging for any number of drivers can be enabled through the config file. 

The format is: 
#DEFINE driver driver
where driver is the filename of the driver.

The debug variable for each driver will be the same across all drivers i.e. DEBUG_ON
I have only changed the ctc driver at the moment as an example.

The config file can be setup with the templates as I have done with the sbc_STD.asm
Try enabling the ctc debug line to see it in effect.

Example output:

```
TASM Z80 Assembler.       Version 3.2 September, 2001.
 Copyright (C) 2001 Squak Valley Software
tasm: pass 1 complete.
SYSTEM TIMER: NONE
HBIOS INT STACK space: 55 bytes.
HBIOS TEMP STACK space: 158 bytes.
dsrtc occupies 697 bytes. Debugging on.
uart occupies 816 bytes. Debugging on.
sio occupies 616 bytes. Debugging on.
vga occupies 1051 bytes. Debugging on.
cvdu occupies 904 bytes. Debugging on.
FONTS 8X16 occupy 1466 bytes.
kbd occupies 1064 bytes. Debugging on.
prp occupies 1397 bytes. Debugging on.
md occupies 449 bytes. Debugging on.
fd occupies 2376 bytes. Debugging on.
ppide occupies 1645 bytes. Debugging on.
term occupies 2091 bytes.
RTCDEF=32
UNLZSA2 for Z80.
HBIOS space remaining: 10906 bytes.
tasm: pass 2 complete.
tasm: Number of errors = 0
```
Let me know if you are happy to proceed.

### CODE REVIEW

**Comment by wwarthen** [comment]
Hi @b1ackmai1er,

Yes, this looks like a pretty good approach.  Just a couple things...

First, my attempts to enable debug in the CTC driver have failed.  I see no definition for "DEBUG_ON" and I get the following error building anything that has CTC enabled (with or without debugging):

`ctc.asm line 0176: Label not found: (DEBUG_ON)`

Is something missing from the check-in?

Second, I am wondering about the naming for enabling debugging.  Using `#DEFINE ctc ctc` to enable debugging in CTC does not seem intuitive.  Can the naming include debug somewhere?  Like ctc_debug?

I'm a little curious why you are using #DEFINEs instead of equates.  Not an issue, just wondered if there was a specific reason.

Thanks!

Wayne

**Comment by wwarthen** [comment]
OK, your last check-in took care of things.  I am now able to build everything and I am able to control CTC debugging as described.

I also now see why you cannot add "_debug" to the controlling names.

So, this seems fine to me.  Do you want this checked in as-is or did you want to propagate the change to the other drivers first?

Thanks,

Wayne

**Comment by b1ackmai1er** [comment]
Hi Wayne,

Yes missing hbios.asm update whixh I have submitted now. Oops.

Agreed about the naming convention.

I was trying to change the driver loading and debugging to be a generic
macro based on the driver name. I kept hitting road blocks with the macro
expansion limitations.

Still thinking about it :)

**Comment by b1ackmai1er** [comment]
Hi Wayne, I am happy to propogate the changes. Im away for a few days so
may not be immediate.

Regards Phil

**Comment by wrljet** [comment]
Wayne, et al, I just wanted to say, I still follow all this work intently.

Bill

**Comment by wwarthen** [comment]
> Wayne, et al, I just wanted to say, I still follow all this work intently.

Great to hear that you do Bill!

**Comment by wwarthen** [comment]
Well, I am having trouble with the new macro under the Linux build.  So, I am going to work through that if possible.  Stay tuned.

-Wayne

**Comment by b1ackmai1er** [comment]
Lol will be prepared to back this out :)

**Comment by wwarthen** [comment]
So, I have not found any way around this.  It appears that the Linux assembler (uz80as) simply does not like any of the '#' prefixed pseudo-ops inside of a macro.  I have not had time to look at the code, but it is probably not something I want to change.

Very sorry about this, but I don't want to leave the Linux and MacOS builds behind.

-Wayne

**Comment by b1ackmai1er** [comment]
No problem, will back thisb
 out when I get home.

So just to confirm, nested conditionals need to be removed. Can #include
remain?

Thanks.

**Comment by wwarthen** [comment]
> So just to confirm, nested conditionals need to be removed.

Yes.

> Can #include remain?

Sadly, no.  It appears that none of the ANSI C preprocessor style directives (the ones that start with a '#') can be nested within a #DEFINEd macro.  I specifically tried #INCLUDE by itself and that also failed.  As soon as the '#' character is seen, uz80as spits out a syntax error and stops.

-Wayne

**Pull request closed without merging**
