### PR TITLE
Dean/yellow msx boards

### PR DESCRIPTION
**Pull request by vipoo**
Hi Wayne,

This PR contains 2 new drivers and a variation to the TMS driver.

It may be of interest to RC2014 users who are building/built the MSX compatible modules I have been developing.
If you would like more details, please ask.

For reference there is:
* the [hackaday project](https://hackaday.io/project/175574-msx-compatible-boards-for-rc2014) and the,
*  [github project](https://github.com/vipoo/yellow-msx-series-for-rc2014)

I believe the changes i am submitting will have no build impact, unless relevant configuration parameters are set.

### V9958 Video support in the TMS(9918) driver

For the TMS change, I have added a new mode `TMSMODE_RCV9958` to support 80 column text for the V9958 video board.  For any other mode, the code should be unchanged - only new code is activated for this new mode.

The new mode sets the registers for the video chip to support 80 column text and also includes some extra delays required by the chip for text mode (compared to the TMS9918 driver)

### MSX Keyboard driver

This driver is in the file `Source/HBIOS/msxkeyb.asm`.  It drives a 8255 PPI chip.

It has default port mappings of: 

```
MKY_REGA		.EQU	$A8
MKY_REGB		.EQU	$A9
MKY_REGC		.EQU	$AA
MKY_REGCMD		.EQU	$AB
```

The source code is derived from some of your existing keyboard drivers in HBIOS, for scan codes processing and such.

This driver can be activated with the configuration entry of 

`MSKENABLE	.SET	TRUE		; MSX 5255 PPI KEYBOARD COMPATIBLE DRIVER (REQUIRES TMS VDA DRIVER)`

This configuration entry will also activate in the keyboard driver within the TMS driver.  In fact, the keyboard driver will only be activated if the TMS video driver is activated. 

### RP5C01 RTC driver

This driver is in the file `Source/HBIOS/rp5rtc.asm`.  

It has default port mappings of:
```
RP5RTC_REG	.EQU	$B4
RP5RTC_DAT	.EQU	$B5
```

This driver can be activated with the following:

`RP5RTCENABLE	.SET	TRUE		; RP5C01 RTC BASED CLOCK (RP5RTC.ASM)`

### Testing

I have tested these drivers on my RC2014 build -- using the new MSX modules with standard RC2014 modules (CPU, Clock, etc)

I have tested under CP/M and Z-SYSTEM.  That includes with the CRTACT set to TRUE to boot up into CRT mode (as well as changing to CRT mode from within CPM)

I also tested using LDDS within Z-SYSTYEM with the RTC module.

Cheers
Dean

### CODE REVIEW

**Comment by wwarthen** [comment]
My apologies Dean.  I have been a bit overloaded.  I should be able to get to this tomorrow.  Sounds great!

Thanks,

Wayne

**Comment by vipoo** [comment]
No need to apologise mate.  Getting the PR organised has been on my task list for quite a while.

Take your time.

Cheers
Dean

**Comment by wwarthen** [comment]
OK, your code is now merged.  Code looks good although I really don't have the hardware to test yet.  I hope to rectify that soon.

I did make one very minor change to tms.asm to correct a build issue when building for the N8 platform.

I do have a few (non-critical) questions:

1. You have added a new VDADEV device code called VDADEV_V9958.  However, I don't see it used anywhere.  Can it be removed?  Or did I miss something?
2. The references to the MSX keyboard seem to vary a lot.  You use MSK for the MSKENABLE flag, MKY as the label prefix in tms.asm, and the name of the driver file is mskkeyb.asm.  Would you mind if I standardize everything by using MKY?
3. There are a few new config settings at the end of RCZ80_std, but I don't think they are actually needed.  One is even a duplicate of one above.  Can you confirm what is intended here?

```
TMSENABLE       .SET    FALSE           ; TMS: ENABLE TMS9918/V9958 VIDEO/KBD DRIVER (TMS.ASM)
TMSMODE         .SET    TMSMODE_RCV9958	; TMS: DRIVER MODE: TMSMODE_[RC/RCV9958]
TMSTIMENABLE	.SET	FALSE		; MS: ENABLE TIMER INTERRUPTS (REQUIRES IM1)
CRTACT		.SET	FALSE		; ACTIVATE CRT (VDU,CVDU,PROPIO,ETC) AT STARTUP
VDAEMU		.SET    EMUTYP_TTY	; VDA EMULATION: EMUTYP_[TTY|ANSI]

RP5RTCENABLE	.SET	FALSE		; RP5C01 RTC BASED CLOCK (RP5RTC.ASM)

MSKENABLE	.SET	FALSE		; MSX 5255 PPI KEYBOARD COMPATIBLE DRIVER (REQUIRES TMS VDA DRIVER)
```

Thanks!

Wayne

**Comment by vipoo** [comment]
Thanks Wayne,

> _I do have a few (non-critical) questions:_

Thats fine - be as critical as you like...  (if u make me cry, it will only make me stronger!)

> _1. You have added a new VDADEV device code called VDADEV_V9958. However, I don't see it used anywhere. Can it be removed? Or did I miss 

Its in tms.asm, line 341:
```

TMS_VDADEV:
#IF (TMSMODE == TMSMODE_RCV9958)
	LD	D, VDADEV_V9958
```

> _2. The references to the MSX keyboard seem to vary a lot. You use MSK for the MSKENABLE flag, MKY as the label prefix in tms.asm, and the name of the driver file is mskkeyb.asm. Would you mind if I standardize everything by using MKY?_

Arrmm --- yes i should have done better here --- i do recall getting a little muddled - be great if you want to go and clean it up and fix up my mistakes 👍 


> _3. There are a few new config settings at the end of RCZ80_std, but I don't think they are actually needed. One is even a duplicate of one above. Can you confirm what is intended here?_

I only added these as a template/guide of the specific build switches that are relevant to my changes.  They are all just mirroring the default values (disabled).  For me it just made it easy to know what I can turn on, during testing, experimenting and making my own final build -- but I understand if it makes more sense to remove them.

Some are pre-existing settings.  The new ones are:
```
TMSMODE         .SET    TMSMODE_RCV9958	; TMS: DRIVER MODE: TMSMODE_[RC/RCV9958]
RP5RTCENABLE	.SET	FALSE		; RP5C01 RTC BASED CLOCK (RP5RTC.ASM)
MSKENABLE	.SET	FALSE		; MSX 5255 PPI KEYBOARD COMPATIBLE DRIVER (REQUIRES TMS VDA DRIVER)
```

I hope they make sense what they are and do....

Cheers
Dean

**Comment by wwarthen** [comment]
Hi Dean,

OK, I did a quick round of minor cleanup stuff.

1. I was still a bit confused by the way that V9958 was implemented as both a device type and as a mode within the TMS device type.  To be consistent with other drivers, V9958 would really be just a mode of the TMS device type.  I have made that change and added a "MODE" field on the boot messages to make it clear what is going on.
2. I standardized the use of "MKY" consistently for all references to the MSX keyboard driver.
3. I removed duplicate entries from the RCZ80_std.asm configuration file.  If I did things correctly, it should still be possible to enable V9958+MSX keyboard by setting MKYENABLE and TMSENABLE to TRUE.

If you detect any issues, please do let me know.  This was a sizable amount of new code -- thanks!

-Wayne

**Pull request merged**
