### PR TITLE
Documentation updates

### PR DESCRIPTION
**Pull request by b1ackmai1er**
Reset subfunction 3
Diagnostics LEDs (please check formatting)

### CODE REVIEW

**Comment by b1ackmai1er** [comment]
ps2iface is looking much better after refactor :)

**Comment by wwarthen** [comment]
Hi @b1ackmai1er,

I did a commit before I saw this PR.  I had to resolve some conflicts, but I think I got it right.

Thanks, Wayne

**Comment by wwarthen** [comment]
@b1ackmai1er 

Nope, I screwed it up.  I will make a new commit in a few minutes to fix this.

Sorry, Wayne

**Comment by wwarthen** [comment]
@b1ackmai1er

OK, I think I straightened it out.  Please make sure to pull the latest from the repo and let me know if you see any problems.  I have tested the latest (with your changes and mine) and it seems to be working well.

Thanks, Wayne

**Pull request merged**
