### PR TITLE
Initial I2C support for PCF8584/DS1307 on ECB-4PIO-I2C

### PR DESCRIPTION
**Pull request by b1ackmai1er**
https://www.retrobrewcomputers.org/doku.php?id=boards:ecb:4pio-i2c:development#software_drivers

Hi Wayne,

Can you please check it build ok?
Plenty more work to do :)

Regards Phil.

### CODE REVIEW

**Comment by wwarthen** [comment]
Looks good @b1ackmai1er.  It is not enabled by default in any of the standard builds, so it should not cause any problems.  I am going to merge the changes and you can improve incrementally as desired.

Thanks!

Wayne

**Comment by wwarthen** [comment]
There are some minor issues with the Linux build -- mostly due to the fact that Linux sorts directories differently than Windows.  I am taking care of it.  Will check-in shortly.

**Comment by wwarthen** [comment]
All good now.

**Comment by wwarthen** [comment]
RTCHB.COM is working for me.  I can't really test RTCDS7.COM lacking the hardware, but note that it fails very badly when the hardware is not present.  Is a hardware presence test possible?

**Comment by b1ackmai1er** [comment]
Yes I should be able to fix that, thanks.

**Pull request merged**
