### PR TITLE
Update ZSM from v4.1 to V4.2

### PR DESCRIPTION
**Pull request by b1ackmai1er**

### CODE REVIEW

**Comment by wwarthen** [comment]
Thank you Phil!

**Comment by b1ackmai1er** [comment]
Hi Wayne,

What does the [O] flag do in the CPM3 build script?

zx LINK -BIOS3[OS]=BIOSKRNL,SCB,BOOT,CHARIO,MOVE,DRVTBL,DISKIO,UTIL

Thanks

**Comment by wwarthen** [comment]
> What does the [O] flag do in the CPM3 build script? zx LINK -BIOS3[OS]=BIOSKRNL,SCB,BOOT,CHARIO,MOVE,DRVTBL,DISKIO,UTIL

To be honest, it is a little mysterious.  The following is quoted from the DRI CP/M 3 System Guide:

> Link the BIOS3.REL or BNKBIOS3.REL file and the SCB.REL file with LINK-80 to produce the BIOS3.SPR or BNKBIOS3.SPR file. The [OS] option with LINK causes the output of a System Page Relocatable (SPR) file.

I have never taken the time to understand exactly what a System Page Relocatable file is.  There is a little more about the file format in Appendix C of the CR/M 3 Programmer's Manual.  I think it is just DRIs version of a relocatable object file.  However, the use of the [OS] option seems to have extra magic that I don't understand.

-Wayne

**Comment by b1ackmai1er** [comment]
Thanks Wayne, cp/m 3 is a total mystery to me.

regards phil

**Pull request merged**
