### PR TITLE
Create ppidetst.asm

### PR DESCRIPTION
**Pull request by lynchaj**
PPIDETST is a debugging tool for building and testing PPIDE interfaces, posted with permission from author

### CODE REVIEW

**Comment by lynchaj** [comment]
this version of PPIDETST builds under z80asm, original builds under TASM so it may be desirable to revert to original version

**Comment by wwarthen** [comment]
Hi Andrew,

I'm very happy to include PPIDETST, but at this time I am putting all changes in the dev branch because I hope to release that very soon.  This PR is against the master branch.

Would you mind re-submitting it against the dev branch?  Alternatively, I would be very happy to take care of it.  Since I want to incorporate it into the build process, I will be doing some work on it anyway.

Thanks!

Wayne

**Comment by lynchaj** [comment]
Hi Wayne,No problem!  I'll reload it against the dev branch
Thanks! Andrew Lynch
    On Tuesday, July 6, 2021, 03:05:06 PM EDT, Wayne Warthen ***@***.***> wrote:  
 
 


Hi Andrew,

I'm very happy to include PPIDETST, but at this time I am putting all changes in the dev branch because I hope to release that very soon. This PR is against the master branch.

Would you mind re-submitting it against the dev branch? Alternatively, I would be very happy to take care of it. Since I want to incorporate it into the build process, I will be doing some work on it anyway.

Thanks!

Wayne

**Comment by wwarthen** [comment]
This has been resubmitted under the dev branch.  Closing this request.

**Pull request closed without merging**
